### ISSUE TITLE
Unable to define custom DNS in dnsmasq.conf

### ISSUE THREAD

**Issue by Matt-Swift** [Kazade/dreampi#23]
A user recently tried to define a different server in `dnsmasq.conf` to play on a different server than the ones dreamcast.online directs you to.

However, there is a stacktrace error from SSL/TLS checks it seems, posted below:

```
 Something went wrong...
#012Traceback (most recent call last):
#012  File "/usr/local/bin/dreampi", line 623, in main
#012    update_dns_file()
#012  File "/usr/local/bin/dreampi", line 69, in update_dns_file
#012    response = urllib2.urlopen(DNS_FILE)
#012  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
#012    return opener.open(url, data, timeout)
#012  File "/usr/lib/python2.7/urllib2.py", line 429, in open
#012    response = self._open(req, data)
#012  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
#012    '_open', req)
#012  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
#012    result = func(*args)
#012  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
#012    context=self._context)
#012  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
#012    h.request(req.get_method(), req.get_selector(), req.data, headers)
#012  File "/usr/lib/python2.7/httplib.py", line 1042, in request
#012    self._send_request(method, url, body, headers)
#012  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
#012    self.endheaders(body)
#012  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
#012    self._send_output(message_body)
#012  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
#012    self.send(msg)
#012  File "/usr/lib/python2.7/httplib.py", line 844, in send
#012    self.connect()
#012  File "/usr/lib/python2.7/httplib.py", line 1263, in connect
#012    server_hostname=server_hostname)
#012  File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket
#012    _context=self)
#012  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
#012    self.do_handshake()
#012  File "/usr/lib/python2.7/ssl.py", line 848, in do_handshake
#012    match_hostname(self.getpeercert(), self.server_hostname)
#012  File "/usr/lib/python2.7/ssl.py", line 282, in match_hostname
#012    % (hostname, ', '.join(map(repr, dnsnames))))
#012CertificateError: hostname 'dreamcast.online' doesn't match either of '$HOSTNAME1', '$HOSTNAME2'
```

**Comment by Matt-Swift** [comment]
Turns out this issue was resolved by updating (who knew?). I didn't realise they were on an old version.

That being said, defining a custom DNS server that's primarily designed to redirect hostname queries to game servers doesn't quite work properly, as it seems DreamPi tries to use this DNS for connecting to a timesyncd server, which naturally never gets a response. Whether you would consider this an issue to work around for DreamPi or the DNS server is your call.

Edit: Seems like the user was able to just get it to work in the end... goodness knows what changes, so feel free to ignore this issue entirely!
