### ISSUE TITLE
Errors while running DreamPi

### ISSUE THREAD

**Issue by Casuallynoted** [Kazade/dreampi#4]
Hello!

I was able to get DreamPi 1.3 running on my device, but for some reason, it wasn't running at startup. I thought maybe I should update the files with the most up to date ones on here, then ran it with --no-daemon and it says:

Traceback (most recent call last):
  File "./dreampi.py", line 396, in <module>
    sys.exit(main())
  File "./dreampi.py", line 384, in main
    config_server.stop()
  File "/home/pi/config_server.py", line 81, in stop
    thread.join()
AttributeError: 'NoneType' object has no attribute 'join'

Did I mess up my install? Is there anything I can do to correct it?

**Comment by Casuallynoted** [comment]
Might help that I get the following error when running config_server:

import.im6: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import.im6: unable to open X server`' @ error/import.c/ImportImageCommand/368.
import.im6: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import.im6: unable to open X server`' @ error/import.c/ImportImageCommand/368.
from: can't read /var/mail/BaseHTTPServer
from: can't read /var/mail/dcnow
./config_server.py: line 10: syntax error near unexpected token `('
./config_server.py: line 10:`class DreamPiConfigurationService(BaseHTTPRequestHandler):'

**Comment by Casuallynoted** [comment]
I totally just realized how stupid I am. These are the Dreampi server files. How can I get the client versions of these files back on my device?

Sorry for the stupid question!

> _<

**Comment by Casuallynoted** [comment]
Fixed by rewriting to my SD card! However, it seems as though the DreamPi isn't listening by default, as in order to make the two lights come on on my modem and for it to receive signals from the TLS, I have to manually run ./dreampi.py --no-daemon
